package model;
// Generated 20 dic 2023 17:56:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dishes generated by hbm2java
 */
public class Dishes implements java.io.Serializable {

	private Integer id;
	private Restaurant restaurant;
	private String name;
	private String description;
	private Double price;
	private Set orderses = new HashSet(0);

	public Dishes() {
	}

	public Dishes(Restaurant restaurant, String name, String description, Double price, Set orderses) {
		this.restaurant = restaurant;
		this.name = name;
		this.description = description;
		this.price = price;
		this.orderses = orderses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
