package model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

    private int id; // Cambiado a tipo int
    private Users users;
    private Double total;
    private Date orderDate; // Nueva propiedad para la fecha
    private String restaurantId; // Nueva propiedad para el ID del restaurante
    private Set<Dishes> disheses = new HashSet<>(0); // Cambiado el tipo a Set<Dishes>

    public Orders() {
    }

    public Orders(int id, Users users, Double total, Date orderDate, String restaurantId, Set<Dishes> disheses) {
        this.id = id;
        this.users = users;
        this.total = total;
        this.orderDate = orderDate;
        this.restaurantId = restaurantId;
        this.disheses = disheses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public Double getTotal() {
        return this.total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public String getRestaurantId() {
        return this.restaurantId;
    }

    public void setRestaurantId(String restaurantId) {
        this.restaurantId = restaurantId;
    }

    public Set<Dishes> getDisheses() {
        return this.disheses;
    }

    public void setDisheses(Set<Dishes> disheses) {
        this.disheses = disheses;
    }
}
