package model;
// Generated 20 dic 2023 17:56:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private int id;
	private Users users;
	private Double total;
	private Set disheses = new HashSet(0);

	public Orders() {
	}

	public Orders(int id, Users users, Double total, Set disheses) {
		this.id = id;
		this.users = users;
		this.total = total;
		this.disheses = disheses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	public Set getDisheses() {
		return this.disheses;
	}

	public void setDisheses(Set disheses) {
		this.disheses = disheses;
	}

}
