package model;
// Generated 20 dic 2023 17:56:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant implements java.io.Serializable {

	private String id;
	private String name;
	private String address;
	private String image;
	private Set disheses = new HashSet(0);

	public Restaurant() {
	}

	public Restaurant(String id, String name, String address, String image, Set disheses) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.image = image;
		this.disheses = disheses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set getDisheses() {
		return this.disheses;
	}

	public void setDisheses(Set disheses) {
		this.disheses = disheses;
	}

}
