/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Michelle Arias
 */
public class CartPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrdersPanel
     */
    public CartPanel() {
        initComponents();
        checkoutBtn.putClientProperty("JComponent.arc", "arc:40");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titleTxt = new javax.swing.JLabel();
        scrollCart = new javax.swing.JScrollPane();
        cart = new javax.swing.JTable();
        menuTxt = new javax.swing.JLabel();
        summaryPanel = new View.PanelRound();
        titleSumTxt = new javax.swing.JLabel();
        subTxt = new javax.swing.JLabel();
        shipTxt = new javax.swing.JLabel();
        totTxt = new javax.swing.JLabel();
        summTxt = new javax.swing.JLabel();
        shippingPrice = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JLabel();
        checkoutBtn = new javax.swing.JButton();
        addMealsBtn = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(255, 255, 255));

        titleTxt.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        titleTxt.setText("My Cart");

        cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollCart.setViewportView(cart);

        menuTxt.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        menuTxt.setForeground(new java.awt.Color(204, 204, 204));
        menuTxt.setText("Menu");

        summaryPanel.setRoundBottomLeft(10);
        summaryPanel.setRoundBottomRight(10);
        summaryPanel.setRoundTopLeft(10);
        summaryPanel.setRoundTopRight(10);

        titleSumTxt.setFont(new java.awt.Font("Nunito Black", 0, 14)); // NOI18N
        titleSumTxt.setText("Payment Summary");

        subTxt.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        subTxt.setForeground(new java.awt.Color(102, 102, 102));
        subTxt.setText("Subtotal");

        shipTxt.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        shipTxt.setForeground(new java.awt.Color(102, 102, 102));
        shipTxt.setText("Shipping");

        totTxt.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        totTxt.setForeground(new java.awt.Color(102, 102, 102));
        totTxt.setText("Total");

        summTxt.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        summTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        summTxt.setText("$120");

        shippingPrice.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        shippingPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shippingPrice.setText("$20");

        totalPriceTxt.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        totalPriceTxt.setForeground(new java.awt.Color(78, 96, 255));
        totalPriceTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPriceTxt.setText("$140");

        checkoutBtn.setBackground(new java.awt.Color(78, 96, 255));
        checkoutBtn.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Checkout");

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shipTxt)
                            .addComponent(titleSumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(summTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shippingPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(totalPriceTxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(14, 14, 14))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleSumTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subTxt)
                    .addComponent(summTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shipTxt)
                    .addComponent(shippingPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totTxt)
                    .addComponent(totalPriceTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        addMealsBtn.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        addMealsBtn.setForeground(new java.awt.Color(78, 96, 255));
        addMealsBtn.setText(" <  Add more meals ");
        addMealsBtn.setBorder(null);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollCart, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(addMealsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollCart, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMealsBtn))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMealsBtn;
    private javax.swing.JPanel background;
    private javax.swing.JTable cart;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel menuTxt;
    private javax.swing.JScrollPane scrollCart;
    private javax.swing.JLabel shipTxt;
    private javax.swing.JLabel shippingPrice;
    private javax.swing.JLabel subTxt;
    private javax.swing.JLabel summTxt;
    private View.PanelRound summaryPanel;
    private javax.swing.JLabel titleSumTxt;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JLabel totTxt;
    private javax.swing.JLabel totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
