/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ForgotPasswordController;
import Controller.SignUpController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Michelle Arias
 */
public class forgotPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public forgotPanel() {
        initComponents();
        instructionsBtn.putClientProperty( "Button.arc","arc:40" );
        inputEmailReset.putClientProperty( "JComponent.arc","arc:40" );
        inputEmailReset.putClientProperty("JTextField.placeholderText", "name@example.com");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        titleTxt = new javax.swing.JLabel();
        inputEmailReset = new javax.swing.JTextField();
        emailTxt = new javax.swing.JLabel();
        instructionsBtn = new javax.swing.JButton();
        descriptionTxt1 = new javax.swing.JLabel();
        backToLoginBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        logo.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/miniLogo.png"))); // NOI18N

        titleTxt.setFont(new java.awt.Font("Nunito", 1, 30)); // NOI18N
        titleTxt.setText("Forgot password");

        emailTxt.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        emailTxt.setText("Email");

        instructionsBtn.setBackground(new java.awt.Color(78, 96, 255));
        instructionsBtn.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        instructionsBtn.setForeground(new java.awt.Color(255, 255, 255));
        instructionsBtn.setText("Send instructions");
        instructionsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instructionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsBtnActionPerformed(evt);
            }
        });

        descriptionTxt1.setFont(new java.awt.Font("Nunito", 0, 11)); // NOI18N
        descriptionTxt1.setForeground(new java.awt.Color(84, 85, 99));
        descriptionTxt1.setText("<html> Enter the email associated with your account and we'll <br>send an email with instructions to reset your password </html>");

        backToLoginBtn.setFont(new java.awt.Font("Nunito SemiBold", 1, 12)); // NOI18N
        backToLoginBtn.setForeground(new java.awt.Color(102, 102, 102));
        backToLoginBtn.setText("<   Back to login");
        backToLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backToLoginBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descriptionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputEmailReset, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instructionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backToLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(logo)
                .addGap(45, 45, 45)
                .addComponent(backToLoginBtn)
                .addGap(24, 24, 24)
                .addComponent(titleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmailReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(instructionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backToLoginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginBtnMousePressed
        // TODO add your handling code here:
          JFrame mainFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
    if (mainFrame instanceof MainLogin) {
        ((MainLogin) mainFrame).loginPanel();
    }
    }//GEN-LAST:event_backToLoginBtnMousePressed

    private void instructionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsBtnActionPerformed
        // TODO add your handling code here:
        if(SignUpController.verificarCredenciales(inputEmailReset.getText())){
            ForgotPasswordController.changePassword(inputEmailReset.getText());
        }else{
            JOptionPane.showMessageDialog(null, "The email is not registred", "User not found", JOptionPane.WARNING_MESSAGE);

        }
        
       
    }//GEN-LAST:event_instructionsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToLoginBtn;
    private javax.swing.JLabel descriptionTxt1;
    private javax.swing.JLabel emailTxt;
    private javax.swing.JTextField inputEmailReset;
    private javax.swing.JButton instructionsBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel titleTxt;
    // End of variables declaration//GEN-END:variables
}
