/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PanelManager;
import static View.RestaurantPanel.cart;
import java.awt.Cursor;
import java.util.List;
import model.Dishes;

/**
 *
 * @author Michelle Arias
 */
public class MainApp extends javax.swing.JFrame {

    /**
     * Creates new form MainApp
     */
    public MainApp() {
        initComponents();
        HomePanel home = new HomePanel();
        this.setLocationRelativeTo(null);
        PanelManager manager = new PanelManager(mainPanel, 800, 550);
        manager.mostrarPanel(home);
        updatePointVisibility();
       
       
    }

     public  void restaurantPanel(List<Dishes> dishesList){
        RestaurantPanel restPanel = new RestaurantPanel(dishesList);
        PanelManager manager = new PanelManager(mainPanel, 800, 550);
        manager.mostrarPanel(restPanel);
    }
     
    public  void updatePointVisibility() {
    System.out.print("Actualizando punto");
    if (cart.isEmpty()) {
        point.setVisible(false); // Ocultar si el carrito tiene elementos
    } else {
        point.setVisible(true); // Mostrar si el carrito está vacío
    }
     point.revalidate();
    point.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topBar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        restaurantsBtn = new javax.swing.JLabel();
        myOrdersBtn = new javax.swing.JLabel();
        verticalSeparator = new javax.swing.JSeparator();
        point = new javax.swing.JLabel();
        shoppingCartBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diseño sin título.png"))); // NOI18N

        restaurantsBtn.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        restaurantsBtn.setText("Restaurants");
        restaurantsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaurantsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restaurantsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restaurantsBtnMouseExited(evt);
            }
        });

        myOrdersBtn.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        myOrdersBtn.setText("My Orders");
        myOrdersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myOrdersBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                myOrdersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                myOrdersBtnMouseExited(evt);
            }
        });

        verticalSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        point.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        point.setForeground(new java.awt.Color(255, 0, 51));
        point.setText(" ●");

        shoppingCartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping.png"))); // NOI18N
        shoppingCartBtn.setBorder(null);
        shoppingCartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shoppingCartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shoppingCartBtnMouseClicked(evt);
            }
        });

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logoutBtn.setBorder(null);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topBarLayout = new javax.swing.GroupLayout(topBar);
        topBar.setLayout(topBarLayout);
        topBarLayout.setHorizontalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(logo)
                .addGap(448, 448, 448)
                .addComponent(restaurantsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(verticalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(myOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(shoppingCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topBarLayout.setVerticalGroup(
            topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topBarLayout.createSequentialGroup()
                .addGroup(topBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(restaurantsBtn))
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(verticalSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(myOrdersBtn))
                    .addComponent(point)
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(shoppingCartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(topBarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        getContentPane().add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, -1, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void restaurantsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantsBtnMouseClicked
        // TODO add your handling code here:
        HomePanel home = new HomePanel();
        PanelManager manager = new PanelManager(mainPanel, 800, 550);
        manager.mostrarPanel(home);
    }//GEN-LAST:event_restaurantsBtnMouseClicked

    private void restaurantsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantsBtnMouseEntered
        // TODO add your handling code here:
       this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_restaurantsBtnMouseEntered

    private void restaurantsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaurantsBtnMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_restaurantsBtnMouseExited

    private void myOrdersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myOrdersBtnMouseEntered
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_myOrdersBtnMouseEntered

    private void myOrdersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myOrdersBtnMouseExited
        // TODO add your handling code here:
        this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_myOrdersBtnMouseExited

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MainLogin m = new MainLogin();
        m.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void myOrdersBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myOrdersBtnMouseClicked
        // TODO add your handling code here:
        OrdersPanel orders = new OrdersPanel();
        PanelManager manager = new PanelManager(mainPanel, 800, 550);
        manager.mostrarPanel(orders);
    }//GEN-LAST:event_myOrdersBtnMouseClicked

    private void shoppingCartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shoppingCartBtnMouseClicked
        // TODO add your handling code here:
        CartPanel cart = new CartPanel();
        PanelManager manager = new PanelManager(mainPanel, 800, 550);
        manager.mostrarPanel(cart);
    }//GEN-LAST:event_shoppingCartBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logo;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel myOrdersBtn;
    private javax.swing.JLabel point;
    private javax.swing.JLabel restaurantsBtn;
    private javax.swing.JButton shoppingCartBtn;
    private javax.swing.JPanel topBar;
    private javax.swing.JSeparator verticalSeparator;
    // End of variables declaration//GEN-END:variables
}
