/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PanelManager;
import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 * Clase de la base del login
 * @author Michelle Arias
 */
public class MainLogin extends javax.swing.JFrame {

    /**
     * Creates new form MainLogin
     */
    public MainLogin() {
        initComponents();
        LoginPanel loginPanel = new LoginPanel();
        PanelManager manager = new PanelManager(containerForms, 400, 600);
        this.setLocationRelativeTo(null);
        manager.mostrarPanel(loginPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        media = new javax.swing.JLabel();
        containerForms = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(105, 123, 255));

        media.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Media.png"))); // NOI18N
        media.setText("jLabel1");

        containerForms.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerFormsLayout = new javax.swing.GroupLayout(containerForms);
        containerForms.setLayout(containerFormsLayout);
        containerFormsLayout.setHorizontalGroup(
            containerFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        containerFormsLayout.setVerticalGroup(
            containerFormsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(containerForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(media, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerForms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(media)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        FlatCyanLightIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new MainLogin().setVisible(true);
                 
            }
        });
    }
    /**
     * Método que instancia el Forgot Panel
     */
    public  void forgotPanel(){
        forgotPanel forgotPanel = new forgotPanel();
        PanelManager manager = new PanelManager(containerForms, 400, 600);
        manager.mostrarPanel(forgotPanel);
    }
    /**
     * Método que instancia el Login Panel
     */
    public  void loginPanel(){
        LoginPanel loginPanel = new LoginPanel();
        PanelManager manager = new PanelManager(containerForms, 400, 600);
        manager.mostrarPanel(loginPanel);
    }
    /**
     * Método que instancia el SignUp Panel
     */
    public  void signUpPanel(){
        SignUpPanel signUp = new SignUpPanel();
        PanelManager manager = new PanelManager(containerForms, 400, 600);
        manager.mostrarPanel(signUp);
    }
    /**
     * Método que desactiva todo lo relacionado al login e inicia el home del app
     */
    public void login(){
         MainLogin.this.dispose();

        // Abre NuevoJFrame
        MainApp nuevoFrame = new MainApp();
        nuevoFrame.setVisible(true);
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel containerForms;
    private javax.swing.JLabel media;
    // End of variables declaration//GEN-END:variables
}
