/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static Controller.EmailValidator.checkEmailFormat;
import Controller.ResetPasswordController;
import Controller.SignUpController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Michelle Arias
 */
public class ResetPasswordPanel extends javax.swing.JFrame {

    /**
     * Creates new form ResetPasswordPanel
     */
    private String userEmail;

    public ResetPasswordPanel() {
        initComponents();
        this.setLocationRelativeTo(null);
        inputCode.putClientProperty("JTextField.placeholderText", "6 characters");
        inputPassword.putClientProperty("JTextField.placeholderText", "min. 8 characters");
        inputRepeat.putClientProperty("JTextField.placeholderText", "min. 8 characters");
    }

    // Método setter para el email
    public void setUserEmail(String email) {
        this.userEmail = email;
        // Aquí puedes actualizar los componentes de la UI si es necesario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titleTxt = new javax.swing.JLabel();
        descriptionTxt1 = new javax.swing.JLabel();
        verificationTxt = new javax.swing.JLabel();
        inputCode = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        repeatTxt = new javax.swing.JLabel();
        inputRepeat = new javax.swing.JPasswordField();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diseño sin título.png"))); // NOI18N

        titleTxt.setFont(new java.awt.Font("Nunito", 1, 30)); // NOI18N
        titleTxt.setText("Reset Password");

        descriptionTxt1.setFont(new java.awt.Font("Nunito", 0, 11)); // NOI18N
        descriptionTxt1.setForeground(new java.awt.Color(84, 85, 99));
        descriptionTxt1.setText("<html>We have sent you a code to your email, enter it to change your password</html>");

        verificationTxt.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        verificationTxt.setText("Verification Code");

        passwordTxt.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        passwordTxt.setText("New Password");

        repeatTxt.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        repeatTxt.setText("Repeat Password");

        resetBtn.setBackground(new java.awt.Color(78, 96, 255));
        resetBtn.setFont(new java.awt.Font("Nunito SemiBold", 0, 12)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Change Password");
        resetBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verificationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                .addComponent(inputRepeat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(repeatTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(titleTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verificationTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCode, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(repeatTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO: add your handling code here:
        String verificationCode = inputCode.getText();
        String cont = String.valueOf(inputPassword.getPassword());
        String cont2 = String.valueOf(inputRepeat.getPassword());

        if (verificationCode.isEmpty() || cont.isEmpty() || cont2.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please complete all fields", "Empty fields", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                if (!cont.equals(cont2)) {
                    JOptionPane.showMessageDialog(null, "Passwords are not the same", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (cont.length() < 8) {
                    JOptionPane.showMessageDialog(null, "Password must be at least 8 characters", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Parseo del código de verificación
                    try {
                        int verifCode = Integer.parseInt(verificationCode);
                        boolean comprueba = SignUpController.verificarCredenciales(userEmail);
                        if (comprueba) {
                            if (ResetPasswordController.verificarCodigoDeVerificacion(userEmail, verifCode)) {
                                ResetPasswordController.updatePassword(userEmail, cont);
                                JOptionPane.showMessageDialog(null, "Password updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                                dispose();
                                MainLogin m = new MainLogin();
                                m.setVisible(true);
                            } else {
                                JOptionPane.showMessageDialog(null, "Invalid verification code", "Error", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "User not found", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Verification code must be numeric", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (ClassCastException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Unexpected error", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPasswordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResetPasswordPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel descriptionTxt1;
    private javax.swing.JTextField inputCode;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JPasswordField inputRepeat;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel passwordTxt;
    private javax.swing.JLabel repeatTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel titleTxt;
    private javax.swing.JLabel verificationTxt;
    // End of variables declaration//GEN-END:variables
}
