/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.UIManager;

/**
 *
 * @author Michelle Arias
 */
public class RestaurantPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public RestaurantPanel() {
        initComponents();
        UIManager.put( "panelRestaurant.arc", 9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        separator = new javax.swing.JSeparator();
        backgroundTitle = new javax.swing.JPanel();
        dessertDiscount = new javax.swing.JLabel();
        dealDessert = new View.PanelRound();

        setBackground(new java.awt.Color(255, 255, 255));

        separator.setForeground(new java.awt.Color(237, 238, 242));

        dessertDiscount.setFont(new java.awt.Font("Nunito ExtraBold", 0, 24)); // NOI18N
        dessertDiscount.setText("Royal Suhi House");

        dealDessert.setBackground(new java.awt.Color(255, 255, 255));
        dealDessert.setRoundBottomLeft(20);
        dealDessert.setRoundBottomRight(20);
        dealDessert.setRoundTopLeft(20);
        dealDessert.setRoundTopRight(20);

        javax.swing.GroupLayout dealDessertLayout = new javax.swing.GroupLayout(dealDessert);
        dealDessert.setLayout(dealDessertLayout);
        dealDessertLayout.setHorizontalGroup(
            dealDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );
        dealDessertLayout.setVerticalGroup(
            dealDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundTitleLayout = new javax.swing.GroupLayout(backgroundTitle);
        backgroundTitle.setLayout(backgroundTitleLayout);
        backgroundTitleLayout.setHorizontalGroup(
            backgroundTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTitleLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(dealDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dessertDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        backgroundTitleLayout.setVerticalGroup(
            backgroundTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(backgroundTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dessertDiscount)
                    .addComponent(dealDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(backgroundTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(backgroundTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundTitle;
    private View.PanelRound dealDessert;
    private javax.swing.JLabel dessertDiscount;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
