package food.model;
// Generated 20 dic 2023 17:56:06 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
        private Integer verificationCode;
	private String email;
	private String password;
	private Set orderses = new HashSet(0);

	public Users() {
	}

	public Users(String email, String password, Set orderses, Integer verificationCode) {
		this.email = email;
		this.password = password;
		this.orderses = orderses;
                this.verificationCode = verificationCode;
	}

	public Integer getId() {
		return this.id;
	}

        public Integer getVerificationCode() {
		return this.verificationCode;
	}
        
	public void setId(Integer id) {
		this.id = id;
	}
        
        public void setVerificationCode(Integer verificationCode) {
		this.verificationCode = verificationCode;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
